# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsvisitcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodschannel',
            options={'ordering': ['group_id', 'sequence'], 'verbose_name': '商品频道', 'verbose_name_plural': '商品频道'},
        ),
        migrations.AlterField(
            model_name='goodschannel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='goods.GoodsCategory', verbose_name='顶级商品类别'),
        ),
    ]
